/*
 * This Java source file was generated by the Gradle 'init' task.
 */
//package app;
import hexlet.code.App;
import hexlet.code.Differ;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertEquals;

class AppTest {
    @Test
    void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    void appJsonDifferGenerate() {
        String filepath1 = "src/test/resources/file1.json";
        String filepath2 = "src/test/resources/file2.json";
        String result = "{"
                + "\n- follow: false"
                + "\n  host: hexlet.io"
                + "\n- proxy: 123.234.53.22"
                + "\n- timeout: 50"
                + "\n+ timeout: 20"
                + "\n+ verbose: true"
                + "\n}";
        String diff = Differ.generate(filepath1, filepath2);
        assertEquals(diff, result);
    }

    @Test
    void appYmlDifferGenerate() {
        String filepath1 = "src/test/resources/file1.yml";
        String filepath2 = "src/test/resources/file2.json";
        String result = "{"
                + "\n- follow: false"
                + "\n  host: hexlet.io"
                + "\n- proxy: 123.234.53.22"
                + "\n- timeout: 50"
                + "\n+ timeout: 20"
                + "\n+ verbose: true"
                + "\n}";
        String diff = Differ.generate(filepath1, filepath2);
        assertEquals(diff, result);
    }
}
